# Logging Configuration

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/cyber_attack_tracer.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  "":  # root logger
    level: INFO
    handlers: [console, file]
    propagate: true

  src:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  src.trace_collector:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  src.analysis_engine:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  src.ember_integration:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  src.knowledge_graph:
    level: DEBUG
    handlers: [console, file]
    propagate: false
